name: Node.js
"on":
  push:
    branches:
    - $default-branch
  pull_request:
    branches:
    - $default-branch
jobs:
  build:
    strategy:
      matrix:
        node-version:
        - 18.x
        - 20.x
        - 22.x
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: SQLadmin
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: SQLadmin
        ports:
        - 3306:3306
    steps:
    - name: ~
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - name: ~
      run: npm ci
    - name: ~
      run: npm run build --if-present
    - name: ~
      run: npm test